commit the MoveFilesToTrashCommand code
AustinCGomez/Python-File-Mover-CLI pull request #41
Opened 2023-10-29 17:06 UTC by Sorena1994

Hi Austin, 

I'm sending the updated code with MoveFilesToTrashCommand class. I'm a beginner dev and would be very happy to have your feedback. 

Best Regards,
Sorena

2023-10-29 18:26 UTC, AustinCGomez commented
Thanks for contributing. I will take a look at it tonight and provide any feedback.

2023-10-30 00:17 UTC, AustinCGomez commented on pythonfilemover/main.py
> +        self.directory_from = None
I am not understanding setting self.directory_from to None.  The user would need to define a from directory as we want to move all files from self.directory_from to the recycle bin.

2023-10-30 00:22 UTC, AustinCGomez requested changes
Great job on working on this commit. I believe that you are almost there to what we need. I did notice two potential errors. 

First: MoveFilesToTrashCommand() would require that a directory_from is selected. I ran the program and it was not working with moving any files since that directory was left to blank. 

Second: In DefineCommand()class within def main(self) there is no click.prompt for --move-to-recycle. I would add one there for --move-to-recylce in a similar fashion to this "--move-folders - Move Entire Folders from Directory A to Directory B!.

2023-10-30 00:22 UTC, AustinCGomez commented on pythonfilemover/main.py
> +        click.echo("Please choose the obtain below to begin: ")
I would recommend changing the 'obtain' to 'option' below.

2023-11-02 15:00 UTC, Sorena1994 commented
Hi Austin, I'm sorry I couldn't respond sooner. I decided to adopt the easier solution as I had to deal with other problems. I used send2trash module and it works. I removed dir_a and dir_b and the class MoveFilesToTrashCommand takes no argument. I have tested it on my pc, and it worked.

2023-11-02 22:25 UTC, AustinCGomez approved these changes

2023-11-03 03:17 UTC, AustinCGomez commented
Hi @Sorena1994 excellent work on the new solution and it does work! I'll have this pull request merged soon.

2023-11-03 03:24 UTC, merged